# Generated by Django 5.1.7 on 2025-04-01 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimages",
            name="details",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_images",
                to="store.productdetails",
            ),
        ),
    ]
