# Generated by Django 5.1.7 on 2025-04-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_productimages_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
